export type Language = 'en' | 'ar';

export const translations = {
  en: {
    title: "Leave & Vacation Tracker",
    signIn: "Sign In",
    email: "Email",
    password: "Password",
    history: "Submission History",
    leaveTracker: "Leave Tracker (Hourly)",
    vacationTracker: "Vacation Tracker (Daily)",
    submit: "Submit Request",
    adminDashboard: "Admin Dashboard",
    notifications: "Notifications",
    sick: "Sick Leave",
    annual: "Annual Leave",
    death: "Bereavement Leave",
    medicalReport: "Medical Report (Required for Paid Sick Leave)",
    missingReportWarning: "These hours will be deducted from your leave balance due to missing medical report.",
    deductedFlag: "Deduction Applied (No Report)",
    createUser: "Create New Employee Account",
    langToggle: "العربية",
    dir: "ltr",
  },
  ar: {
    title: "نظام إدارة الإجازات والمغادرات",
    signIn: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    history: "سجل الطلبات",
    leaveTracker: "طلب مغادرة (بالساعات)",
    vacationTracker: "طلب إجازة (بالأيام)",
    submit: "تقديم الطلب",
    adminDashboard: "لوحة تحكم المسؤول",
    notifications: "التنبيهات",
    sick: "إجازة مرضية",
    annual: "إجازة سنوية",
    death: "إجازة وفاة",
    medicalReport: "التقرير الطبي (مطلوب للإجازات المرضية)",
    missingReportWarning: "سيتم خصم هذه الساعات/الأيام من رصيدك لعدم إرفاق التقرير الطبي.",
    deductedFlag: "خصم بدون تقرير",
    createUser: "إنشاء حساب موظف جديد",
    langToggle: "English",
    dir: "rtl",
  }
};